ci: rename ReSukiSU workflows to BakaSU
Change-Id: I658d3e51dff4ed87723493c495e240c042e4b461
Signed-off-by: gyabii <gyabii@proton.me>

diff --git a/.github/workflows/bakasu-build-susfs.yml b/.github/workflows/bakasu-build-susfs.yml
--- a/.github/workflows/bakasu-build-susfs.yml
+++ b/.github/workflows/bakasu-build-susfs.yml
@@ -1,11 +1,15 @@
-# build.yml kanged from Rezoss Reza modified to build kernel with ReSukiSU and SuSFS using the main branch
-name: Build permissive kernel (ReSukiSU, SuSFS, `main` branch)
+# build.yml kanged from Rezoss Reza modified to build kernel with BakaSU and SuSFS using the main branch
+name: Build kernel (BakaSU, SuSFS, `main` branch)
 on:
   workflow_dispatch:
+  schedule:
+    - cron: '30 5 * * 1'
 
 jobs:
   build:
     runs-on: ubuntu-latest
+    permissions:
+       contents: write
     steps:
       - name: Checkout the repository
         uses: actions/checkout@v6
@@ -14,7 +18,7 @@ jobs:
         run: |
           sudo apt update
           sudo apt install -y --no-install-recommends \
-            bc bison build-essential wget flex \
+            bc bison build-essential wget flex gh \
             g++-multilib gcc-multilib git gnupg \
             lib32readline-dev lib32z1-dev \
             libelf-dev liblz4-tool libssl-dev \
@@ -25,41 +29,23 @@ jobs:
         run: |
           wget -q https://github.com/gyabii/kernel_samsung_sm8550-common/releases/download/anykernel/anykernel.zip
 
-      - name: Apply ReSukiSU with SuSFS
+      - name: Apply BakaSU with SuSFS
         run: |
           set -euxo pipefail
-
-          # Determine the current kernel version
           echo "KERNEL_VERSION=$(grep -m1 '^SUBLEVEL =' ./Makefile | awk '{print $3}')" >> $GITHUB_ENV
-
-          # Integrate ReSukiSU
-          curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/refs/heads/main/kernel/setup.sh" | bash -s main
-
-          # Integrate SuSFS
+          curl -LSs "https://raw.githubusercontent.com/Baka-SU/BakaSU/refs/heads/main/kernel/setup.sh" | bash -s main
           git clone --depth=1 https://gitlab.com/gyabi/susfs4ksu.git -b gki-android13-5.15
-
           SUSFS_KERNEL_PATCH="susfs4ksu/kernel_patches/50_add_susfs_in_gki-android13-5.15.patch"
           patch -p1 < "$SUSFS_KERNEL_PATCH"
-
           mkdir -p fs
           mkdir -p include/linux
-
-          # Always replace fs/susfs.c
           cp -f susfs4ksu/kernel_patches/fs/susfs.c fs/susfs.c
-
-          # Always replace include/linux/susfs.h
           cp -f susfs4ksu/kernel_patches/include/linux/susfs.h include/linux/susfs.h
-
-          # Always replace include/linux/susfs_def.h
           cp -f susfs4ksu/kernel_patches/include/linux/susfs_def.h include/linux/susfs_def.h
-  
           for f in fs/susfs.c include/linux/susfs.h include/linux/susfs_def.h; do
             if [ -f "$f" ]; then echo "Found: $f"; else echo "Missing: $f"; fi
           done
-          
-          # Clean up SUSFS repo (we only needed kernel patches, not KSU integration)
           rm -rf susfs4ksu
-
           CONFIG_FILE=arch/arm64/configs/gki_defconfig
           cat >> "$CONFIG_FILE" << 'EOF'
           CONFIG_KSU=y
@@ -90,28 +76,50 @@ jobs:
         run: |
           git config --global user.email "gyabii@proton.me"
           git config --global user.name "gyabii"
-          patch -p1 < ".github/goodies/permissive.patch"
           chmod +x scripts/build.sh
           ./scripts/build.sh 2>&1 | tee "$GITHUB_WORKSPACE/build.log"
+          if [ ! -f "out/arch/arm64/boot/Image.gz" ]; then
+            echo "ERROR: Kernel compilation failed! out/arch/arm64/boot/Image.gz not found."
+            exit 1
+          fi
 
       - name: Package image with AnyKernel3
         id: package
         run: |
-          echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
+          BUILD_DATE="$(date)"
+          TIMESTAMP="$(date +%d%m%y-%H%M%S)"
           set -euxo pipefail
           unzip "anykernel.zip" -d anykernel/
           cp out/arch/arm64/boot/Image.gz anykernel/
-          # Build final name
-          ZIP_NAME="common-5.15.${KERNEL_VERSION}-gyabii_resukisu-permissive-susfs-$(date +%d%m%y-%H%M%S)"
+          touch -a -m -t 200901010000.00 "anykernel/Image.gz"
+          ZIP_NAME="common-5.15.${KERNEL_VERSION}-gyabii_bakasu-susfs-$(date +%d%m%y-%H%M%S)"
           cd anykernel
           zip -r0 ../"${ZIP_NAME}".zip ./*
-          echo "zip_path=$GITHUB_WORKSPACE/${ZIP_NAME}.zip" >> "$GITHUB_OUTPUT"
-          echo "zip_name=${ZIP_NAME}" >> "$GITHUB_OUTPUT"
           cd ..
+          HASH=$(sha256sum "${ZIP_NAME}.zip" | awk '{print $1}')
+          cat >> "release_notes.md" << EOF
+          Built at: ${BUILD_DATE}
+          
+          sha256:
+          \`\`\`
+          ${HASH}
+          \`\`\`
+          EOF
+          echo "zip_full_path=$GITHUB_WORKSPACE/${ZIP_NAME}.zip" >> "$GITHUB_OUTPUT"
+          echo "zip_name=${ZIP_NAME}.zip" >> "$GITHUB_OUTPUT"
+          echo "tag_name=common-bakasu-5.15.${KERNEL_VERSION}-${TIMESTAMP}" >> "$GITHUB_OUTPUT"
 
       - name: Upload the flashable kernel
         uses: actions/upload-artifact@v7
         with:
-          name: ${{steps.package.outputs.zip_name}}
+          name: ${{ steps.package.outputs.zip_name }}
           path: anykernel/
-          
+
+      - name: Publish to GitHub Release
+        uses: softprops/action-gh-release@v3
+        with:
+          name: "BakaSU + SuSFS 5.15.${{ env.KERNEL_VERSION }} common kernel"
+          tag_name: ${{ steps.package.outputs.tag_name }}
+          files: ${{ steps.package.outputs.zip_full_path }}
+          body_path: release_notes.md
+          make_latest: false
